server:
  port: 8080
spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm
    time-zone: Asia/Tashkent # Ixtiyoriy: vaqt belbog'ini belgilash
  datasource:
    url: jdbc:postgresql://localhost:5432/event_booking_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    url: /api-docs
  default-produces-media-type: application/json

app:
  jwt:
    secret: "aVeryStrongAndLongSecretKeyForJWTThatIsHardToGuess"
    expiration-ms: 86400000
