server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm
    time-zone: Asia/Tashkent
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/event_booking_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  default-produces-media-type: application/json

app:
  jwt:
    secret: "aVeryStrongAndLongSecretKeyForJWTThatIsHardToGuess"
    expiration-ms: 86400000
